apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test
spec:
  replicas: 1
  selector: 
     matchLabels:
       env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: java-app
         image: osos3/java-test:latest
         ports:
           - containerPort: 80